# Generated by Django 2.1.2 on 2018-10-30 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100)),
                ('rut', models.CharField(help_text='Ej: 12.123.123-1', max_length=12, unique=True)),
                ('nombre', models.CharField(help_text='Nombre Completo', max_length=60)),
                ('fechaNac', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.CharField(help_text='region', max_length=60)),
                ('ciudad', models.CharField(help_text='ciudad', max_length=60)),
                ('tipoVivienda', models.CharField(help_text='vivienda', max_length=60)),
            ],
        ),
    ]
