# Generated by Django 2.1.2 on 2018-10-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='correo',
            field=models.CharField(max_length=100),
        ),
    ]
